services:
  dev:
    image: portfolio-website:dev
    build:
      context: "${DEV_DIR:-./}/docker/server"
    ports:
      - "${DEV_PORT:-8000}:${DEV_PORT:-8000}"
    environment:
      - PORT=${DEV_PORT}
    volumes:
      - ${DEV_DIR:-./}:/app
    command:
      - bash
      - -c
      - 'make run PORT=${PORT:-8000} || (rm -rf node_modules && make install) && make run PORT=${PORT:-8000}'

  test:
    image: portfolio-website:test
    build:
      context: "${TEST_DIR:-./}/docker/server"
    ports:
      - "${TEST_PORT:-8001}:${TEST_PORT:-8001}"
    environment:
      - PORT=${TEST_PORT}
    volumes:
      - ${TEST_DIR:-./}:/app
    command:
      - bash
      - -c
      - 'make build || (rm -rf node_modules && make install && make build) && make serve PORT=${PORT:-8001}'
